origin/task3
maxim65610/ReturnBot2 pull request #13
Opened 2024-10-18 12:55 UTC by Discobombulator

all is ok?

2024-10-19 20:25 UTC, vpyzhyanov requested changes
есть куда расти

2024-10-19 20:25 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> + * Унаследован от класса DatabaseConnection.
очень плохо, что унаследован. Нарушена парадигма наследования. Этот класс к `DatabaseConnection` никакого отношения не имеет. Это всё равно, что домашнее задание от ручки наследовать.

2024-10-19 20:25 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +     * @ DB_URL URL базы данных
вот для кого вы это пишете? И зачем?

2024-10-19 20:25 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +        try (Connection conn = DriverManager.getConnection(getDB_URL(), getDB_USER(), getDB_PASSWORD());
> Нарушена парадигма наследования. Этот класс к DatabaseConnection никакого отношения не имеет.

Эта строчка тому доказательство

2024-10-19 20:25 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +        String sql = "SELECT * FROM AnswersData WHERE id_question = ?";
имена переменных должны быть осмысленные, уточните что за запрос

2024-10-19 20:25 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +        return sql;
О_о вы же вроде данные хотели получить? При чём тут запрос?

Вы точно уверены, что в случае ошибки вы хотите её "проглотить" и вернуть SQL?

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +        assertEquals(System.getenv("bdUrl"), connection.getDB_URL());
тест абсолютно ничего не тестирует. Во время выполнения теста эти значения абсолютно всегда пустые.

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +        assertEquals("Nice", connection.createAllTable());
тест абсолютно ничего не тестирует. Как думаете почему?

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +        assertEquals("notNice", connection.createAllTable());
тест абсолютно ничего не тестирует. Как думаете почему?

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +public class DatabaseConnectionTest {
нет ни одного теста, который хоть что-то тестирует

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/DepartInfoBDTest.java
>      @Test
обычно аннотация пишется после описания

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/DepartInfoBDTest.java
> +     * Тест для метода по подтягиванию данных из дб
если бы этот тест тестировал обращение к БД, то он бы всегда падал.

А так очень смешной тест))))) А всё из-за странного параметра `textToSend`. **В общем тест тоже ничего не тестирует**

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/LogicForTestABITest.java
> +    private Map<Long, String> resultsTestAbi;
не используется

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/LogicForTestABITest.java
> +        logicForTestABI.retrieveData = retrieveDataMock;  // Замена реального объекта на мок
нарушение инкапсуляции. Вместо этого используйте конструктор

2024-10-19 20:25 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +    RetrieveData retrieveData = new RetrieveData();
нарушение инкапсуляции

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/LogicForTestABITest.java
> +        assertEquals("awaiting_testABI_1", userStates.get(userId));
на самом деле это должна быть сугубо внутренняя реализация, которую **никто** не видит и о ней не знает, даже тест

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/MessageLogicTest.java
> +        assertEquals("Вы начали проходить тестирование по выбору факультета," +
смысл в такой проверке отсутствует. Просто повторили антипример из лекции по тестированию

2024-10-19 20:25 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            else if("/test".equals(messageText)){
случайно увидел, что задача сделана не по постановке. Там такой команды нет. Сдать такую задачу не получится.

2024-10-19 20:25 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            else if("/result".equals(messageText)){
то же самое

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/MessageLogicTest.java
> +class MessageLogicTest {
не увидел тестов на команды:

`/testAbit - запускает опросник, /testres - выводит его результат.`

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/LogicForTestABITest.java
> +public class LogicForTestABITest {
нет теста на то, что этот класс вообще вызывается. В первую очередь я ожидаю увидеть тесты на новые команды в MessageLogicTest

2024-10-19 20:25 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/MessageLogicTest.java
> +        assertEquals("Вот все факультеты которые есть в институте ХТИ:", answer3);
повтор антипримера по тестам

2024-10-20 07:12 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +        return "notNice";
Если вопрос про возврат "notNice", то он используется в тесте, если нет я не понял вопрос

2024-10-21 06:25 UTC, Discobombulator commented on pom.xml
> +            <artifactId>postgresql</artifactId>
fixed

2024-10-21 06:25 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/Main.java
>          /**
fixed

2024-10-21 06:25 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/Main.java
> +        databaseConnection.createAllTable();
fixed

2024-10-21 06:26 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +    public  String getDB_PASSWORD() {
fixed

2024-10-21 06:26 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +        String sql1 = """
fixed

2024-10-21 06:27 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +     * @ DB_URL URL базы данных
fixed

2024-10-21 06:27 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +        String sql2 = """
fixed

2024-10-21 06:27 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            else if("/test".equals(messageText)){
fixed

2024-10-21 06:28 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
> +    private EmailSender emailSender;
fixed

2024-10-21 06:28 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/Main.java
>          String password = System.getenv("passwordForMail"); // Ваш пароль (или App Password)
fixed

2024-10-21 06:28 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
> +    private String inst3CommandReceived() {return "Вот все факультеты которые есть в институте ХТИ:";}
fixed

2024-10-21 06:28 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
>   * Включает методы для обработки команд пользователя и отправки электронных писем.
fixex

2024-10-21 06:28 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
>          return "Привет, этот бот может помочь тебе понять куда ты хочешь поступить," +
fixed

2024-10-21 06:29 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
> +    private String inst3CommandReceived() {return "Вот все факультеты которые есть в институте ХТИ:";}
fixed

2024-10-21 06:29 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
> +    private EmailSender emailSender;
fixed

2024-10-21 06:30 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
>       * Метод для установки объекта EmailSender.
fixed

2024-10-21 06:30 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
> +public class MessageLogic {
fixed

2024-10-21 06:30 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
> +    public  String worksWithMail(Update update, String messageText, Long userId, String currentState, Map<Long, String> userStates, Map<Long, String> userMails) {
fixed

2024-10-21 06:30 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
>      public String slogic(String messageText) {
fixed

2024-10-21 06:34 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +    private Map<Long, String> userStatesforTest = new HashMap<>();
fixed

2024-10-21 06:35 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> + * @ DB_URL URL базы данных
fixed

2024-10-21 06:36 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +public class DepartInfoBD {
fixed

2024-10-21 06:36 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +    String user =databaseConnection.getDB_USER();
fixed

2024-10-21 06:38 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +
fixed

2024-10-21 06:38 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +    public String takeInfo(String data,String textToSend) {
fixed

2024-10-21 06:38 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +     * @param data Идентификатор для поиска информации.
fixed

2024-10-21 06:40 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/KeyboardLogic.java
> +            row.add(new InlineKeyboardButton().builder().text(list_with_dataBD.get(1)).callbackData(list_with_dataBD.get(4)).build());
fixed

2024-10-21 06:40 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +    private Map<Long, Integer> id_testABI = new HashMap<>();
fixed

2024-10-21 06:41 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +    public List<String> arrayBDforTestABI(int id_testABI){
fixed

2024-10-21 06:44 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +    public String getnamefacultyfromBD(int id_getfaculty){
fixed

2024-10-21 06:44 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +        for(int i = 1000; i < 1013; i++) {
fixed

2024-10-21 06:44 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +        for(int i =0 ;i < sizeListofABIechoice; i++){
fixed

2024-10-21 06:45 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +    public void setResultsTestAbi(Map<Long, String> results) {
fixed

2024-10-21 06:47 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> + * Унаследован от класса DatabaseConnection.
fixed

2024-10-21 06:51 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +    RetrieveData retrieveData = new RetrieveData();
fixed

2024-10-21 06:56 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +        return "notNice";
fixed

2024-10-21 07:02 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +     * @ DB_URL URL базы данных
fixed

2024-10-21 07:02 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +        try (Connection conn = DriverManager.getConnection(getDB_URL(), getDB_USER(), getDB_PASSWORD());
fixed

2024-10-21 12:41 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +    private Map<Long, String> userStatesforTest = new HashMap<>();
fixed

2024-10-21 12:46 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            // Обработка исключения (опционально: логирование)
fixed

2024-10-21 12:52 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
>          try {
fixed 2/3

2024-10-21 12:54 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +    String url = databaseConnection.getDB_URL();
fixed

2024-10-21 12:55 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +        return textToSend;
так надо, если у нас не находится данных по бд нам надо вернуть сообщение после обработки message logic, а не перед чем и является data

2024-10-21 12:58 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +     * @param textToSend Текст, возвращаемый при отсутствии информации.
fixed

2024-10-21 13:47 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +            data_BD = arrayBDforTestABI(id_testABI.get(userId) + 2);
fixed

2024-10-21 14:03 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +            return "Вам больше всего подходит факультет: " + resultsTestAbi.get(chatID);
Теперь MessageLogic обрабатывает только простые случаи, не зависящие от других объектов/классов, теперь он называться CommonMessageLogic. fixed

2024-10-21 14:03 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +            return  "Вы еще не прошли тест) ";
Теперь MessageLogic обрабатывает только простые случаи, не зависящие от других объектов/классов, теперь он называться CommonMessageLogic. fixed

2024-10-21 14:04 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            else if("/test".equals(messageText)){
Теперь MessageLogic обрабатывает только простые случаи, не зависящие от других объектов/классов, теперь он называться CommonMessageLogic. fixed

2024-10-21 14:06 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +        String sql = "SELECT * FROM AnswersData WHERE id_question = ?";
fixed

2024-10-21 14:06 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +            return "Вам больше всего подходит факультет: " + resultsTestAbi.get(chatID);
Теперь MessageLogic обрабатывает только простые случаи, не зависящие от других объектов/классов, теперь он называться CommonMessageLogic. fixed

2024-10-21 14:07 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +        return sql;
fixed

2024-10-21 14:21 UTC, Discobombulator commented on src/test/java/io/proj3ct/ReturnBot1/MessageLogicTest.java
> +        assertEquals("Вы начали проходить тестирование по выбору факультета," +
fixed

2024-10-21 15:48 UTC, Discobombulator commented on src/test/java/io/proj3ct/ReturnBot1/MessageLogicTest.java
> +        assertEquals("Вот все факультеты которые есть в институте ХТИ:", answer3);
fixed

2024-10-21 15:49 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            else if("/result".equals(messageText)){
fixed

2024-10-21 15:58 UTC, Discobombulator commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +        assertEquals(System.getenv("bdUrl"), connection.getDB_URL());
fixed

2024-10-28 20:14 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/Main.java
>           * LogicBrain отвечает за логику работы бота, а TelegramBot
что было не понятно?

![image](https://github.com/user-attachments/assets/80ef8443-1843-404b-8b0c-8ab3ef69d4b3)

2024-10-28 20:19 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +    private String DB_URL;
зачем? Методов для их изменения вы всё равно не добавили

2024-10-28 20:19 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +    public  String getDB_PASSWORD() {
не исправлено. Методы доступа к учётным данным по прежнему доступны извне

2024-10-28 20:19 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/Main.java
> +        databaseConnection.createAllTable();
![image](https://github.com/user-attachments/assets/d4c32351-f897-4de8-8467-d144bd909753)

Не исправлено! DatabaseConnection по прежнему не используется

2024-10-28 20:19 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/Main.java
> +        databaseConnection.createAllTable();
Не исправлено!

2024-10-28 20:21 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +    private final String DB_URL;
не исправлено. В чём сложность?

2024-10-28 20:24 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +        String sql1 = """
Исправлено неправильно. AnswersDataTable не говорит о том, что это запрос и уж тем более не говорит о том, что это **запрос создания таблицы** AnswersData. Даже имя не в Java стиле. Лучше `createAnswersDataTableQuery `

2024-10-28 20:28 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +        String DepartsInfoTable = """
аналогично исправлено неправильно

2024-10-28 20:28 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +        try (Connection conn = DriverManager.getConnection(databaseConnection.getDB_URL(),
не исправлено. DatabaseConnection можно выкидывать на помойку, его задачу по прежнему выполняются все, кроме него

2024-10-28 20:28 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +        return "ERROR";
Это что такое? Надо убрать. Все ошибки должны быть в исклчючениях

2024-10-28 20:28 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +        return "notNice";
Вы пишете код для теста? Или тест для кода?

2024-10-28 20:32 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +    public TelegramBot(String name, String token, CommonMessageLogic logic, EmailSender emailSender, EmailLogic emailLogic, LogicForTestABI logicForTestABI) {
А если ваша программа будет усложняться, то будете писать здесь миллион аргументов? Нет, так не пойдёт

2024-10-28 20:32 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
>   * Включает методы для обработки команд пользователя и отправки электронных писем.
удаление - не выход. Очень зря удалили класс. 

> класс должен только сообщения обрабатывать

теперь видимо TelegramBot этим не занимается. Но это не его задача

2024-10-28 20:33 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
>          return "Привет, этот бот может помочь тебе понять куда ты хочешь поступить," +
Не исправлено! Эти методы лишённые смысла как были так и есть, просто они в других классах остались

2024-10-28 20:40 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +    // TODO: Обработать случаи, когда update не содержит callbackQuery или message,
похоже код ещё сырой, зачем скинули пулл реквест тогда?

2024-10-28 20:40 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            // TODO: Логирование ошибки отправки сообщения
где?

2024-10-28 20:40 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            // TODO: Логирование ошибки отправки сообщения
где?

2024-10-28 20:40 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            // TODO: Логирование ошибки отправки сообщения
где?

2024-10-28 20:40 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
>          try {
Не исправлено! Вы правда думаете, что удаление `@Override` решает какую-то проблем? Нет, это её создаёт. Почитайте что такое `@Override` и зачем он нужен

2024-10-28 20:40 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
> +    public  String worksWithMail(Update update, String messageText, Long userId, String currentState, Map<Long, String> userStates, Map<Long, String> userMails) {
пишите конкретно что исправлено. Никакого исправления не вижу. Даже метод приватным не стал

2024-10-28 20:43 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/CommonMessageLogic.java
> + * Включает методы для обработки команд пользователя.
метод не делает то, что в нём написано. Он обрабатывает только некоторые команды.

2024-10-28 20:43 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/CommonMessageLogic.java
> +        return CommonMessageConstants.DEFAULT_RESPONSE;
Не исправлено!

2024-10-28 20:43 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
>      public String slogic(String messageText) {
Не исправлено! Удаление - не выход

2024-10-28 20:46 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/CommonMessageLogic.java
> +    public String handleMessage(String messageText) {
этот класс не делает то, что написано в его описании. Ведь он никак не связан ни с обработкой почты, ни клавиатуры. Вообще отдельно стоит в сторонке и ничего значимого не делает.

Не так надо было исправлять замечание. Не надо было удалять MessageLogic, надо было исправлять замечание

2024-10-28 20:46 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            else if("/test".equals(messageText)){
Исправлено неправильно. И вы сказали неправду, MessageLogic  был удалён, хотя я явно говорил, что не надо никого удалять.

Пожалуй дальше смотреть не буду, по любому там тоже ничего не исправлено.

2024-10-28 20:47 UTC, vpyzhyanov requested changes
Большинство замечаний не исправлено

2024-10-29 02:45 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/Main.java
> +        databaseConnection.createAllTable();
fixed

2024-10-29 02:47 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +    private final String DB_URL;
fixed

2024-10-29 02:54 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +    public  String getDB_PASSWORD() {
fixed

2024-10-29 02:55 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +        String sql1 = """
fixed

2024-10-29 02:56 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +        return "notNice";
fixed еще в тот раз

2024-10-29 03:03 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +    private String DB_URL;
fixed

2024-10-29 03:10 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/Main.java
> +        databaseConnection.createAllTable();
fixed

2024-10-29 03:10 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +        String DepartsInfoTable = """
fixed

2024-10-29 03:10 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +        try (Connection conn = DriverManager.getConnection(databaseConnection.getDB_URL(),
fixed

2024-10-29 03:12 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +        return "ERROR";
fixed

2024-10-29 03:15 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            // TODO: Логирование ошибки отправки сообщения
fixed

2024-10-29 03:15 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            // TODO: Логирование ошибки отправки сообщения
fixed

2024-10-29 13:06 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
>          try {
fixed

2024-10-29 13:20 UTC, Discobombulator commented on src/test/java/io/proj3ct/ReturnBot1/DepartInfoBDTest.java
> +     * Тест для метода по подтягиванию данных из дб
Тестов на дб больше не будет, тк это внешний источник

2024-10-29 13:21 UTC, Discobombulator commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +        assertEquals(System.getenv("bdUrl"), connection.getDB_URL());
Тестов на дб больше не будет, тк это внешний источник

2024-10-29 13:21 UTC, Discobombulator commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +        assertEquals("Nice", connection.createAllTable());
Тестов на дб больше не будет, тк это внешний источник

2024-10-29 13:21 UTC, Discobombulator commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +        assertEquals("notNice", connection.createAllTable());
Тестов на дб больше не будет, тк это внешний источник

2024-10-29 13:22 UTC, Discobombulator commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +public class DatabaseConnectionTest {
Тестов на дб больше не будет, тк это внешний источник

2024-10-29 13:25 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            // TODO: Логирование ошибки отправки сообщения
fixed

2024-10-29 13:35 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/CommonMessageLogic.java
> +        return CommonMessageConstants.DEFAULT_RESPONSE;
fixed

2024-10-31 11:00 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
>   * Включает методы для обработки команд пользователя и отправки электронных писем.
мы вынесли все в отдельный класс LogicController , исправлено

2024-10-31 11:01 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
>          return "Привет, этот бот может помочь тебе понять куда ты хочешь поступить," +
fixed

2024-10-31 11:03 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
>      public String slogic(String messageText) {
fixed

2024-10-31 11:05 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +            else if("/test".equals(messageText)){
всю логику , которая была в update, вынесли в  LogicController

2024-10-31 11:14 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +     * @param userStatesforTest состояние теста для каждого пользователя
fixed

2024-10-31 11:24 UTC, maxim65610 commented on src/test/java/io/proj3ct/ReturnBot1/LogicForTestABITest.java
> +        assertEquals("awaiting_testABI_1", userStates.get(userId));
fixed

2024-10-31 12:00 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +    public TelegramBot(String name, String token, CommonMessageLogic logic, EmailSender emailSender, EmailLogic emailLogic, LogicForTestABI logicForTestABI) {
fixed

2024-11-03 18:47 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/Main.java
> +        databaseConnection.createAllTable();
Будьте добры, для более сложных случаев, как этот, пишите как именно исправили. Это существенно ускорит проверку

2024-11-03 18:55 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> + * Класс для подключения к базе данных и создания таблиц
чтобы начало вырисовываться ООП, надо сделать так, что бы этот класс решал только одну задачу. Сейчас он решает несколько. Пусть занимается подключением к БД, а вот созданием таблиц пусть занимается отдельный сервис

2024-11-03 18:55 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +    private final String DB_URL;
Нет ответа на вопрос! Если и дальше пойдёт игра в молчанку и замечания не будут исправляться (особенно когда вы пишете, что якобы их исправили), то сначала получите предупреждение, а потом будет исключены из группы extra

2024-11-03 18:58 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +        return "notNice";
Нет ответа на вопрос! Если и дальше пойдёт игра в молчанку и замечания не будут исправляться (особенно когда вы пишете, что якобы их исправили), то сначала получите предупреждение, а потом будет исключены из группы extra

2024-11-03 19:28 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> + * Класс для подключения к базе данных и создания таблиц
fixed

2024-11-03 19:29 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> + * Класс для подключения к базе данных и создания таблиц
https://github.com/maxim65610/ReturnBot2/pull/27/commits/bc6d894d68c1fe256c825374b5365f22bba873f6

2024-11-03 19:38 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicСontroller.java
> +public class LogicСontroller {
прошу обращать внимание на предупреждения в среде разработки. Использована русская буква

2024-11-03 19:38 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +    final Map<Long, LogicСontroller> logicController = new HashMap<>();
1. Не лучшая идея под каждого пользователя делать разный контроллер. Во первых это очень не эффективно по памяти, этот класс создаёт вместе с собой кучу объектов. Во вторых вы всё равно вынуждены получать chatId и всё равно внутри должны работать с пользователем, никак при этом не контролируя с кем вы работаете, это увеличивает вероятность ошибки и размазывает ответственность
2. инкапсуляция вышла погулять и не вернулась
3. Имя переменно не соответствует её сути. Как будь-то там один контроллер, но это не так. 

Гораздо лучше работать с пользователем на уровне данных, а не на уровне обработки сообщений

2024-11-03 19:38 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +        sendMessage(userId, logicСontroller.getListStringWithTextToSendAndOptionForKeyboard(update, userId));
вот отличный пример где может разорваться связь контроллера с пользователем. Тут может оказаттся другой пользователь.

2024-11-03 19:38 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +    final Map<Long, LogicСontroller> logicController = new HashMap<>();
Самое забавное, что вы так и делаете. Но тут вы видимо решили усложнить код на ровном месте. Вообще непонятно зачем.

2024-11-03 19:38 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
> +    public  String worksWithMail(Update update, String messageText, Long userId, String currentState, Map<Long, String> userStates, Map<Long, String> userMails) {
нет ответа(((( Как со стенкой разговариваю((((

2024-11-03 19:39 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +    private Map<Long, String> userStatesforTest = new HashMap<>();
Нет ответа!

2024-11-03 19:41 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +    private LogicForTestABI logicForTestABI = new LogicForTestABI();
Нет ответа! С чего вы решили, что это риторический вопрос?

2024-11-03 19:47 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +        return textToSend;
По моему комментарию можно было догадаться, что так не надо делать. Так можно делать только если вы хотите максимально запутать всех разработчиков, чтобы никто ничего не понял.

DepartmentsInfo не должен заниматься отправкой сообщения пользователю. В случае отсутствия данных используйте Optional.empty() либо null.

2024-11-03 19:49 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +     * @param textToSend Текст, возвращаемый при отсутствии информации.
Опять нет ответа!

Зачем-то добавили в JavaDoc информацию для поля которого тут быть не должно. Вот кому нужен этот текст (я имею в виду класс, который его использует), вот там используйте и пишите. А тут - не надо

2024-11-03 19:51 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +     * @param data Идентификатор для поиска информации.
Не исправлено! Вообще ничего не изменилось! Ну как так-то? Что тогда вы исправили?

2024-11-03 19:52 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +            data_BD = arrayBDforTestABI(id_testABI.get(userId) + 2);
И как я должен догадаться что именно вы исправили?

2024-11-03 19:53 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +        for(int i = 1000; i < 1013; i++) {
Не исправлено!

![image](https://github.com/user-attachments/assets/7e1f4c1d-04aa-41d5-a0c6-da26153a5530)

2024-11-03 19:59 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +                return "Данные не найдены для id_question: " + id;
ребят, пора начать учиться, уже 2 раз пишу одно и то же замечание. Класс, который `Извлекает данные из базы данных для теста` не должен общаться с пользователем. Он выполняет не свою задачу!

2024-11-03 19:59 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +        assertEquals("notNice", connection.createAllTable());
Нет ответа на вопрос!!!!

2024-11-03 20:01 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +        assertEquals("notNice", connection.createAllTable());
Если не хотите думать и учиться, то надо переходить в простую группу

2024-11-03 20:03 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/LogicForTestABITest.java
> +    private Map<Long, String> resultsTestAbi;
Замечание **проигнорировано**!

2024-11-03 20:04 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +                return "Данные не найдены для id_question: " + id;
Он и не общается это обработка ошибки, чтобы если что-то шло не так, мы в чате видели эти проблемы

2024-11-03 20:05 UTC, vpyzhyanov commented on src/test/java/io/proj3ct/ReturnBot1/LogicForTestABITest.java
> +        assertEquals("awaiting_testABI_1", userStates.get(userId));
А как же прибрать за собой неиспользуемые поля?

2024-11-03 20:09 UTC, vpyzhyanov requested changes
Как исправите, можете мёрджить

2024-11-03 20:17 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +                return "Данные не найдены для id_question: " + id;
это делается с помощью исключений и только с помощью них. В вашем случае он именно общается, притом выдавая ошибку, за корректный ответ

2024-11-04 06:06 UTC, Discobombulator commented on src/test/java/io/proj3ct/ReturnBot1/DatabaseConnectionTest.java
> +        assertEquals("notNice", connection.createAllTable());
Этих тестов уже давно не существует

2024-11-04 06:09 UTC, Discobombulator commented on src/test/java/io/proj3ct/ReturnBot1/LogicForTestABITest.java
> +    private Map<Long, String> resultsTestAbi;
Тоже, это старые тесты которых уже нету, они переписаны

2024-11-04 06:10 UTC, Discobombulator commented on src/test/java/io/proj3ct/ReturnBot1/LogicForTestABITest.java
> +        assertEquals("awaiting_testABI_1", userStates.get(userId));
Тоже, это старые тесты которых уже нету, они переписаны

2024-11-04 06:13 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/RetrieveData.java
> +                return "Данные не найдены для id_question: " + id;
fixed

2024-11-04 06:17 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/Main.java
> +        databaseConnection.createAllTable();
Хорошо

2024-11-04 06:19 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatabaseConnection.java
> +    private final String DB_URL;
исправлено неделю назад

2024-11-04 06:35 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/MessageLogic.java
> +    public  String worksWithMail(Update update, String messageText, Long userId, String currentState, Map<Long, String> userStates, Map<Long, String> userMails) {
я сделал этот метод private

2024-11-04 06:36 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/TelegramBot.java
> +    private Map<Long, String> userStatesforTest = new HashMap<>();
я перенес это в класс LogicForTestABI

2024-11-04 06:38 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +        return textToSend;
исправлено , возвращает null

2024-11-04 06:41 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/DepartInfoBD.java
> +     * @param textToSend Текст, возвращаемый при отсутствии информации.
исправлено

2024-11-04 06:42 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +            data_BD = arrayBDforTestABI(id_testABI.get(userId) + 2);
я переделал эту логику циклом for, теперь строк кода намного меньше и стало читабельнее

2024-11-04 06:49 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> +        for(int i = 1000; i < 1013; i++) {
теперь все исправлено

2024-11-04 06:51 UTC, maxim65610 commented on src/test/java/io/proj3ct/ReturnBot1/LogicForTestABITest.java
> +        logicForTestABI.retrieveData = retrieveDataMock;  // Замена реального объекта на мок
мы переписали этот тест и там это исправлено

2024-11-04 06:53 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/CommonMessageLogic.java
> +    public String handleMessage(String messageText) {
исправленр

2024-11-04 06:54 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicСontroller.java
> +public class LogicСontroller {
хорошо, исправлено

2024-11-07 09:26 UTC, merged