task4
maxim65610/ReturnBot2 pull request #36
Opened 2024-11-18 07:47 UTC by Discobombulator

How many mistakes

2024-11-19 19:48 UTC, vpyzhyanov requested changes
Как исправите, можете мёрджить

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +                return textForMessage.setTheText("registration");
что это такое? Как это понимать? Читается как `установить текст "registration"`. Вообще непонятно что это значит и зачем.

Если внимательно приглядеться, становиться понятно, что смысла в этом классе нет. В данном случае вызов легко заменить на `return MessageConstants.AUTHORISATION_COMMAND_RESPONSE`. Притом без всякой логики и бессмысленных усложнений

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +                if (classNumber <= 11 && classNumber >= 1) {
вот было бы здорово, если бы вы научились хотя бы методы создавать. Вместо того, чтобы делать огромные методы сплошным текстом.

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +            if (emailSender.isValidEmail(messageText)) {
а то абсолютно вся логика в одном методе. Это не ООП, это называется "свалка" или "бардак"

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TextForMessage.java
> + * ооп не выходил погулять)
ну как вам сказать. Этот класс, это всё равно, что ядерная бомба сброшенная на ООП. От него даже мокрого места не осталось. Уж не знаю что вы нашли в нём удобным, было бы гораздо удобнее, если его бы не было. Например все обращения заменяются прямым обращением к константам, например `MessageConstants.REGISTRATION_COMMAND_RESPONSE`

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TextForMessage.java
> +    public String setTheText(String messageText) {
название и описание противоречат друг другу. Метод вообще ничего не устанавливает.

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TextForMessage.java
> +        String response = getMessageMap(messageText);
название не соответствует тому, что метод делает. Никакой Map он не возвращает.

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/TextForMessage.java
> +        messageMap.put("ХТИ", MessageConstants.INST_CHTI_COMMAND_RESPONSE);
если можно просто вернуть константу, то смысла во всём этом классе не вижу никого

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/EmailLogic.java
>  package io.proj3ct.ReturnBot1;
было бы здорово, если бы вы научились создавать пакеты. И разделять их по функционалу или по предметной области. Например будет здорово, если команды будут в одном пакете, а то, что работает с БД в другом. И т.д.

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicController.java
> +    private final LogicAndDataForRegistrationUsers logicAndDataForRegistrationUsers
уверенный шаг в тёмную сторону. Ну очень много полей.

Вот применили бы решение, которое я на паре всем показывал, о том как правильно организовать работу с командами, то проблем бы не было.

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicController.java
> +    public void setDepartmentsInfo(DepartmentsInfo departmentsInfo) {
удаляем

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicController.java
>      private String checkWhatTodo(String data) {
смысл этого метода для меня - загадка

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicController.java
> +            else if("/userDataDell".equals(messageText)){
команд становится слишком много. Пора их разносить по классам

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicForChangeDataUsers.java
> +public class LogicForChangeDataUsers {
даже описание кричит о том, что вы перегрузили класс функционалом. Ему тяжело.

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicForChangeDataUsers.java
> +    public String getUserStatesForChangeData(Long chatID) {
вы уж определитесь, либо это простой контейнер данных. Либо класс который содержит какую-то логику.

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicForChangeDataUsers.java
> +    public String worksWithChangeData(String messageText, Long userId, EmailSender emailSender) {
по моему, этот метод должен быть единственный публичный метод в этом классе

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicForChangeDataUsers.java
> +            if (messageText.equals("/userDataChangeName")) {
пора учиться создавать методы. Тут точно можно создать разные методы по обработке разных состояний

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> -      Экземпляр класса RetrieveData, используемый для получения данных из базы данных.
зачем убрали JavaDoc? Верните обратно

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/MessageConstants.java
> +            "\nЕсли хотите проверить данные воспользуйтесь /userInfo" +
1. перенос на следующую строку принято писать в конце строки, а не в начале.
2. Тут удобно использовать многострочный комментарий. Начинается с `"""`

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +public class UsersData {
название и описание противоречат друг другу. Одно говорит о том, что это просто данные пользователя. А второе - класс для работы с данными хранящимися во внешнем источнике. Данные и работа с данными, это совершенно разные вещи.

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            System.out.println("Ошибка вставки данных: " + e.getMessage());
вы уже изучили исключения. Самое время начать ими пользоваться. Это как раз тот случай.

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            e.getMessage();
это зачем?

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            }
а смысл?

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            System.out.println("Ошибка обновления данных: " + e.getMessage());
не надо "проглатывать" ошибки. Учитесь работать с исключениями

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            }
абсолютно одинаковый бессмысленный код

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            e.getMessage();
и тут всё то же самое

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +    public String takeData(Long userId,DatabaseConnection databaseConnection ) {
`getRegistrationData`

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +        return "Вы не прошли регистрацию";
Опять ООП нарушили. Этот класс за общение с пользователем точно отвечать не должен. Вы сами написали, что он нужен для работы с данными.

Используйте исключения

2024-11-19 19:48 UTC, vpyzhyanov commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +        return "Вы не прошли регистрацию";
аналогично

2024-11-19 20:17 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/EmailLogic.java
>  package io.proj3ct.ReturnBot1;
Это уже реализованно в 5ом таске

2024-11-20 06:23 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatebaseTables.java
> +            Connection conn = databaseConnection.connect();
fixed

2024-11-20 07:04 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TextForMessage.java
> +        messageMap.put("ХТИ", MessageConstants.INST_CHTI_COMMAND_RESPONSE);
fixed

2024-11-20 07:04 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TextForMessage.java
> +        String response = getMessageMap(messageText);
fixed

2024-11-20 07:04 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TextForMessage.java
> +    public String setTheText(String messageText) {
fixed

2024-11-20 07:04 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TextForMessage.java
> +    public String getMessageMap(String messageText){
fixed

2024-11-20 07:04 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/TextForMessage.java
> + * ооп не выходил погулять)
fixed

2024-11-20 07:14 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicForTestABI.java
> -      Экземпляр класса RetrieveData, используемый для получения данных из базы данных.
Вернул

2024-11-20 07:25 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/MessageConstants.java
> +            "\nЕсли хотите проверить данные воспользуйтесь /userInfo" +
Реализовал многострочные сообщения через """

2024-11-20 07:26 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +public class UsersData {
Переделал

2024-11-20 07:38 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            e.getMessage();
убрал

2024-11-20 07:38 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            }
убрал

2024-11-20 07:38 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            }
убрал

2024-11-20 07:39 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            e.getMessage();
убрал

2024-11-20 07:46 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +        return "Вы не прошли регистрацию";
поправил

2024-11-20 07:46 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +    public String takeData(Long userId,DatabaseConnection databaseConnection ) {
переименовал

2024-11-20 07:47 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +        return "Вы не прошли регистрацию";
тоже поправил

2024-11-20 08:31 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +    public DatabaseConnection getDatabaseConnection() {return databaseConnection;}
fixed

2024-11-20 08:31 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +    public String getSurnameUser (Long chatID) {return surnameUser .get(chatID);}
fixed

2024-11-20 08:35 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +    public String getMailUser (Long chatID) {return mailUser .get(chatID);}
Сеттеров больше нету

2024-11-20 08:36 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +    public void setUsersData(UsersData usersData) {this.usersData = usersData;}
Все сеттеры убраны

2024-11-20 08:36 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +    public void setDatabaseConnection(DatabaseConnection databaseConnection) {this.databaseConnection = databaseConnection;}
удалил

2024-11-20 08:36 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +    public void setTextForMessage(TextForMessage textForMessage) {this.textForMessage = textForMessage;
Все сеттеры убраны

2024-11-20 08:36 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +                return textForMessage.setTheText("registration");
сделанно

2024-11-20 08:39 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicController.java
> +    public void setDepartmentsInfo(DepartmentsInfo departmentsInfo) {
удалил

2024-11-20 08:39 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/LogicController.java
>      private String checkWhatTodo(String data) {
удалил

2024-11-20 08:57 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            System.out.println("Ошибка обновления данных: " + e.getMessage());
сделано

2024-11-20 08:57 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/UsersData.java
> +            System.out.println("Ошибка вставки данных: " + e.getMessage());
сделано

2024-11-20 08:58 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatebaseTables.java
> +                System.out.println("Не удалось создать таблицу: соединение с базой данных не установлено.");
сделано

2024-11-20 08:58 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/DatebaseTables.java
> +            System.out.println("Ошибка создания таблицы: " + e.getMessage());
сделано

2024-11-21 11:15 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/EmailLogic.java
> +    public void setUsersData(UsersData usersData) {
исправлено

2024-11-21 11:15 UTC, maxim65610 commented on src/test/java/io/proj3ct/ReturnBot1/EmailLogicTest.java
> +        emailLogic.setUsersData(usersDataMock);
исправлено

2024-11-21 11:45 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +    private final Map<Long, String> mailUser  = new HashMap<>();
исправлено

2024-11-21 11:45 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +public class LogicAndDataForRegistrationUsers {
исправлено

2024-11-21 11:53 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +                if (classNumber <= 11 && classNumber >= 1) {
исправлено

2024-11-21 11:54 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +            if (emailSender.isValidEmail(messageText)) {
исправлено

2024-11-22 11:49 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicAndDataForRegistrationUsers.java
> +    private TextForMessage textForMessage = new TextForMessage();
исправлено

2024-11-22 11:50 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicController.java
> +    private final LogicAndDataForRegistrationUsers logicAndDataForRegistrationUsers
исправлено

2024-11-22 11:50 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicController.java
> +            else if("/userDataDell".equals(messageText)){
исправлено

2024-11-22 11:52 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForChangeDataUsers.java
> +public class LogicForChangeDataUsers {
исправлено

2024-11-22 11:55 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForChangeDataUsers.java
> +    public String worksWithChangeData(String messageText, Long userId, EmailSender emailSender) {
да, но еще есть один геттер

2024-11-22 11:59 UTC, maxim65610 commented on src/main/java/io/proj3ct/ReturnBot1/LogicForChangeDataUsers.java
> +            if (messageText.equals("/userDataChangeName")) {
исправлено

2024-11-22 16:19 UTC, Discobombulator commented on src/main/java/io/proj3ct/ReturnBot1/EmailLogic.java
> +    private final Map<Long, String> userStatesForMail = new HashMap<>();
готово

2024-11-22 16:32 UTC, merged